<#
.SYNOPSIS
    Retrieves scheduled task process creation events from local, remote or offline event logs.
.DESCRIPTION
    Searches for scheduled task process creation events (Event ID 129) from the
    "Microsoft-Windows-TaskScheduler/Operational" log. It supports filtering by task name,
    process ID, priority and time range. It can query local logs, remote computers or .evtx files.
    This is useful for auditing task execution behavior and correlating with task start and completion events.
.EXAMPLE
    PS C:\> Get-EventScheduledTaskProcess -StartTime (Get-Date).AddHours(-1)
    Retrieves scheduled task process creation events from the last hour on the local system.
.EXAMPLE
    PS C:\> Get-EventScheduledTaskProcess -ComputerName "Server01" -Credential (Get-Credential) -TaskName "BackupTask"
    Retrieves process creation events for the "BackupTask" scheduled task from a remote computer.
.EXAMPLE
    PS C:\> Get-EventScheduledTaskProcess -Path "C:\Logs\TaskScheduler.evtx" -ProcessId "1234"
    Retrieves task process creation events from an offline .evtx file filtered by process ID.
#>
function Get-EventScheduledTaskProcess {
    [CmdletBinding(DefaultParameterSetName = 'Local')]
    param (
        # Log name for where the events are stored.
        [Parameter(Mandatory = $false,
                   ValueFromPipelineByPropertyName = $true)]
        [string]
        $LogName = 'Microsoft-Windows-TaskScheduler/Operational',

        # Name of scheduled task. 
        [Parameter(Mandatory = $false,
                   ValueFromPipelineByPropertyName = $true)]
        [string[]]
        $TaskName,

        # Process ID of created task.
        [Parameter(Mandatory = $false,
                   ValueFromPipelineByPropertyName = $true)]
        [string[]]
        $ProcessId,

        # Process Priority.
        [Parameter(Mandatory = $false,
                   ValueFromPipelineByPropertyName = $true)]
        [string[]]
        $Priority,

        # Specifies the path to the event log files that this cmdlet get events from. Enter the paths to the log files in a comma-separated list, or use wildcard characters to create file path patterns. Function supports files with the .evtx file name extension. You can include events from different files and file types in the same command.
        [Parameter(Mandatory=$true,
                   Position=0,
                   ParameterSetName="file",
                   ValueFromPipelineByPropertyName=$true)]
        [Alias("FullName")]
        [ValidateNotNullOrEmpty()]
        [SupportsWildcards()]
        [string[]]
        $Path,


        # Gets events from the event logs on the specified computer. Type the NetBIOS name, an Internet Protocol (IP) address, or the fully qualified domain name of the computer.
        # The default value is the local computer.
        # To get events and event logs from remote computers, the firewall port for the event log service must be configured to allow remote access.
        [Parameter(Mandatory = $true,
                   ValueFromPipelineByPropertyName = $true,
                   ParameterSetName = 'Remote')]
        [string[]]
        $ComputerName,

        # Specifies a user account that has permission to perform this action.
        #
        # Type a user name, such as User01 or Domain01\User01. Or, enter a PSCredential object, such as one generated by the Get-Credential cmdlet. If you type a user name, you will
        # be prompted for a password. If you type only the parameter name, you will be prompted for both a user name and a password.
        [Parameter(Mandatory = $false,
                   ParameterSetName = 'Remote')]
        [Management.Automation.PSCredential]
        [Management.Automation.CredentialAttribute()]
        $Credential,

        # Specifies the maximum number of events that are returned. Enter an integer. The default is to return all the events in the logs or files.
        [Parameter(Mandatory = $false,
                   ValueFromPipelineByPropertyName = $true)]
        [int64]
        $MaxEvents,

        # Start time from where to pull events.
        [Parameter(Mandatory = $false)]
        [datetime]
        $StartTime,

        # End time from where to pull events.
        [Parameter(Mandatory = $false)]
        [datetime]
        $EndTime,

        # Changes the default logic for matching fields from 'and' to 'or'.
        [Parameter(Mandatory = $false)]
        [switch]
        $ChangeLogic,

        # Changes the query action from inclusion to exclusion when fields are matched.
        [Parameter(Mandatory = $false)]
        [switch]
        $Suppress
    )

    begin {
        $Params = $MyInvocation.BoundParameters
        
    }

    process {
        Search-EventLogEventData -EventId 129 -ParamHash $Params -Provider "Microsoft-Windows-TaskScheduler" -RecordType "ScheduledTaskProcess"

    }

    end {}
}
