<#
.SYNOPSIS
    Retrieves PowerShell script block invocation events from local or remote event logs or .evtx files.
.DESCRIPTION
    Searches for PowerShell script block invocation events (Event ID 4104) from the
    "Microsoft-Windows-PowerShell/Operational" log or from specified .evtx files.
    It supports filtering by time range, script block ID and logic modifiers.
    It can query local logs, remote computers or offline event log files.
.EXAMPLE
    PS C:\> Get-EventPsScriptBlock -StartTime (Get-Date).AddHours(-2)
    Retrieves PowerShell script block events from the last 2 hours on the local system.
.EXAMPLE
    PS C:\> Get-EventPsScriptBlock -Path "C:\Logs\PowerShell.evtx"
    Retrieves script block events from the specified .evtx file.
.EXAMPLE
    PS C:\> Get-EventPsScriptBlock -ComputerName "DC01" -Credential (Get-Credential) -ScriptBlockId "abc123"
    Retrieves script block events from a remote computer filtered by a specific ScriptBlock ID.
#>
function Get-EventPsScriptBlock {
    [CmdletBinding(DefaultParameterSetName='none')]
    [Alias()]
    [OutputType([PSObject])]
    Param (

        # Log name of where to look for the PowerShell events.
        [Parameter(Mandatory=$false,
                   ValueFromPipelineByPropertyName=$true,
                   Position=0)]
        [string]
        $LogName = 'Microsoft-Windows-PowerShell/Operational',

        # Specifies the path to the event log files that this cmdlet get events from. Enter the paths to the log files in a comma-separated list, or use wildcard characters to create file path patterns. Function supports files with the .evtx file name extension. You can include events from different files and file types in the same command.
        [Parameter(Mandatory=$true,
                    Position=0,
                    ParameterSetName="file",
                    ValueFromPipelineByPropertyName=$true)]
        [Alias("FullName")]
        [ValidateNotNullOrEmpty()]
        [SupportsWildcards()]
        [string[]]
        $Path,


        # Gets events from the event logs on the specified computer. Type the NetBIOS name, an Internet Protocol (IP) address, or the fully qualified domain name of the computer.
        # The default value is the local computer.
        # To get events and event logs from remote computers, the firewall port for the event log service must be configured to allow remote access.
        [Parameter(Mandatory = $true,
                    ValueFromPipelineByPropertyName = $true,
                    ParameterSetName = 'Remote')]
        [string[]]
        $ComputerName,

        # Specifies a user account that has permission to perform this action.
        #
        # Type a user name, such as User01 or Domain01\User01. Or, enter a PSCredential object, such as one generated by the Get-Credential cmdlet. If you type a user name, you will
        # be prompted for a password. If you type only the parameter name, you will be prompted for both a user name and a password.
        [Parameter(Mandatory = $false,
                    ParameterSetName = 'Remote')]
        [Management.Automation.PSCredential]
        [Management.Automation.CredentialAttribute()]
        $Credential,

        # Specifies the maximum number of events that are returned. Enter an integer. The default is to return all the events in the logs or files.
        [Parameter(Mandatory = $false,
                    ValueFromPipelineByPropertyName = $true)]
        [int64]
        $MaxEvents,

        # Start time from where to pull events.
        [Parameter(Mandatory = $false)]
        [datetime]
        $StartTime,

        # End time from where to pull events.
        [Parameter(Mandatory = $false)]
        [datetime]
        $EndTime,

        # Changes the default logic for matching fields from 'and' to 'or'.
        [Parameter(Mandatory = $false)]
        [switch]
        $ChangeLogic,

        # Changes the query action from inclusion to exclusion when fields are matched.
        [Parameter(Mandatory = $false)]
        [switch]
        $Suppress,

        # ScriptBlock ID GUID that identifies the specific scriptblock on the system. This value is unique per host. 
        [Parameter(Mandatory = $false)]
        [string]
        $ScriptBlockId
    )

    Begin {
        $Params = $MyInvocation.BoundParameters
    }
    Process {

        Search-EventLogEventData -EventId 4104 -ParamHash $Params -Provider "Microsoft-Windows-PowerShell" -RecordType "PSScriptBlock" -ReturnRecord | ForEach-Object -Process {
            [xml]$evtXml = $_.toxml()
            $evtInfo = [ordered]@{}
            $evtInfo['EventId'] = $evtXml.Event.System.EventID
            $evtInfo['EventRecordID'] = $evtXml.Event.System.EventRecordID
            $evtInfo['TimeCreated'] = [datetime]$evtXml.Event.System.TimeCreated.SystemTime
            $evtInfo['Computer'] = $evtXml.Event.System.Computer
            $evtInfo['Provider'] = $evtXml.Event.System.Provider.Name
            $evtInfo['ProcessID'] = $evtXml.Event.System.Execution.ProcessID
            $evtInfo['ThreadID'] = $evtXml.Event.System.Execution.ThreadID
            $evtInfo['UserSID'] = $evtXml.Event.System.Security.UserID
            $evtxml.Event.EventData.Data | ForEach-Object {
                $evtInfo[$_.name] = $_.'#text'
            }
            New-Object psobject -Property $evtInfo
        }

    }
    End {}
}